version: "3.8"
services:
  django_app:
    build:
      context: django_app
    command:
      - /bin/sh
      - "-c"
      - "/django_app/entrypoint.sh"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/django_app/static/
      - media_volume:/django_app/media/


  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_app
    volumes:
      - static_volume:/django_app/static/
      - media_volume:/django_app/media/
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/certbot/data:/var/www/certbot
    env_file:
      - .env

  redis:
    image: redis

  celery-beat:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    command: celery -A django_app beat --loglevel=info -S django
    env_file:
      - .env
    volumes:
      - ./django_app:/django_app
      - static_volume:/django_app/static/
      - media_volume:/django_app/media/
    depends_on:
      - redis

  celery-worker:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    command: celery -A django_app worker --loglevel=info --scheduler django
    env_file:
      - .env
    volumes:
      - ./django_app:/django_app
      - static_volume:/django_app/static/
      - media_volume:/django_app/media/
    depends_on:
      - redis

volumes:
  static_volume:
  media_volume:
