# Generated by Django 4.2.8 on 2024-05-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_courseuserstatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseuserstatus",
            unique_together={("user", "course")},
        ),
        migrations.AddField(
            model_name="courseuserstatus",
            name="installation_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="courseuserstatus",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseuserstatus",
            unique_together={("user", "course"), ("installation_id", "course")},
        ),
    ]
