# Generated by Django 4.2.8 on 2024-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_courseuserstatus_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseuserstatus",
            name="installation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="courseuserstatus",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("installation_id__isnull", True), ("user__isnull", True), _connector="OR"
                ),
                name="installation_id_and_user_cannot_be_null",
            ),
        ),
    ]
