# Generated by Django 4.2.8 on 2024-05-23 19:44

from django.db import migrations, models

import courses.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0005_remove_courseuserstatus_installation_id_and_user_cannot_be_null_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="attachment",
            field=models.FileField(
                upload_to=courses.models.upload_to_course_attachments,
                validators=[courses.models.validate_pdf_file],
            ),
        ),
    ]
