# Generated by Django 4.2.8 on 2024-05-23 20:44

from django.db import migrations, models

import courses.models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_course_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="attachment",
            field=models.FileField(
                editable=False,
                upload_to=courses.models.upload_to_course_attachments,
                validators=[courses.models.validate_pdf_file],
            ),
        ),
    ]
